<!--
  ps5-native-app-boilerplate - Host-side build frontend project.
  Copyright (C) 2026 BlackBearReloaded
  SPDX-License-Identifier: GPL-3.0-or-later
-->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\.deps\SharpProspero\tools\SharpProspero.Link\SharpProspero.Link.csproj" />
    <ProjectReference Include="..\..\.deps\SharpProspero\tools\SharpProspero.Prx\SharpProspero.Prx.csproj" />
  </ItemGroup>
</Project>
